# Generated by Django 5.1.7 on 2025-03-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_interface_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_methods',
            field=models.CharField(max_length=20),
        ),
    ]
