# Generated by Django 5.1.7 on 2025-03-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_interface_app', '0004_remove_transaction_payment_methods_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='order_id',
            field=models.CharField(max_length=255),
        ),
    ]
