# Generated by Django 5.1.7 on 2025-03-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_interface_app', '0005_alter_transaction_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_status',
            field=models.CharField(choices=[('2', 'Fail'), ('1', 'Success'), ('3', 'Pending')], default='3', max_length=20),
        ),
    ]
