# Generated by Django 5.1.7 on 2025-03-27 06:59

import django.core.validators
import multiselectfield.db.fields
import vendor_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=255)),
                ('vendor_type', models.CharField(choices=[('KS', 'Kirana Shop'), ('OC', 'Online Commerce'), ('RE', 'Restaurant'), ('OT', 'Other')], default='OT', max_length=2)),
                ('vendor_contact', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number.', regex='^\\d{10}$')])),
                ('vendor_website', models.URLField(blank=True, null=True)),
                ('vendor_address', models.TextField()),
                ('bank_name', models.CharField(max_length=255)),
                ('ifsc_code', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid 11-character IFSC code.', regex='^[A-Z]{4}0[A-Z0-9]{6}$')])),
                ('account_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid bank account number (9-18 digits).', regex='^\\d{9,18}$')])),
                ('payment_methods', multiselectfield.db.fields.MultiSelectField(choices=vendor_app.models.Vendor.get_payment_method_choices, max_length=20)),
                ('fee_bearer', models.CharField(choices=[('0', 'Vendor Pays'), ('1', 'Customer Pays')], default='0', max_length=1)),
                ('onboarding_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
